_home:
    path: /
    defaults: 
        _controller: SiteBundle:Home:index
_contact:
    path: /contact
    defaults:
        _controller: SiteBundle:Contact:init
_cars:
    path: /vehicules
    defaults:
        _controller: SiteBundle:Car:initList
_car:
    path: /vehicules/{car_id}/{car_title}
    defaults:
        _controller: SiteBundle:Car:initDetail
_blog:
    path: /actualites
    defaults:
        _controller: SiteBundle:Actualites:initList
_blog_item:
    path: /actualites/26458948/preparation-moteur-mgb
    defaults:
        _controller: SiteBundle:Actualites:initDetail